### ISSUE TITLE
Executable name conflict in Ubuntu 14.04

### ISSUE THREAD

**Issue by noquierouser** [alallier/reload#13]
I had recently faced [this issue](http://askubuntu.com/questions/455870/nodejs-hangs-on-ubuntu-14-04-boot-big-cpu-memory-usage) after installing the `reload` package through `npm` using the `-g` flag.

The executable name, `reload`, is in conflict with the actually existing `reload` executable located at `/sbin/reload`, which belongs to [the `initctl` program suite](http://manpages.ubuntu.com/manpages/lucid/en/man8/initctl.8.html) in Ubuntu 14.04. This causes the system to attempt to run `reload` at boot with root permissions and consume CPU usage and HDD activity.

Steps to replicate this issue:
1. `sudo npm install -g reload`
2. Reboot system

I don't know yet what other consequences this might have at system level, as I don't know which routines are affected by running `reload` at system boot.

This issue might also affect other versions of Ubuntu, or even other Linux distros.

**Comment by yamboy1** [comment]
I had just installed reload when I saw this. I looked in /sbin and found a reload executable on Ubuntu 16.04. Straight away I uninstalled it. The developer should change the package name to something like reloadPage that isn't an executable in Ubuntu. How ever really good tool. Will reinstall when name is changed.

**Comment by alallier** [comment]
Thank you @yamboy1 for bringing our attention to this again. It is confirmed that Ubuntu 16.04 has it's own executable named reload. We will need to draft a conversation here on what we would rename our command line executable too. Paging @jprichardson.

**Comment by jprichardson** [comment]
@yamboy1 is `reload` part of the default Ubuntu installation?

**Comment by kethinov** [comment]
Yes. It is a system command installed by default on Ubuntu installations:

```
$ reload --help
Usage: reload [OPTION]... JOB [KEY=VALUE]...
Send HUP signal to job.

Options:
      --session               use existing D-Bus session bus to connect to init daemon (for testing)
      --system                use D-Bus system bus to connect to init daemon
      --dest=NAME             destination well-known name on D-Bus bus
      --user                  run in user mode (as used for user sessions)
  -q, --quiet                 reduce output to errors only
  -v, --verbose               increase output to include informational messages
      --help                  display this help and exit
      --version               output version information and exit

JOB is the name of the job that is to be sent the signal, this may be followed by zero or more environment
variables to distinguish between job instances.
```

**Comment by AckerApple** [comment]
reload has a fork named ack-reload. They work almost identically, especially the commands. Try it out on Ubuntu : https://www.npmjs.com/package/ack-reload#commands

Everything is ack-reload instead of reload

**Comment by yamboy1** [comment]
Maybe this should be renamed to node-reload.

**Comment by alallier** [comment]
Thanks to a friend of mine that did some testing, I'm going to give a short summary.

First, I really don't want to give up the name reload for our command line utility.

So the problem lies that the path in Ubuntu `/usr/bin` comes before `/sbin`. When installing reload globally it will install reload (our package) to `/usr/bin` and the system utility sits in `/sbin`. This means that when the system tries to reach the system command reload it will hit our reload.

So Ubuntu users can either:

* Swap `/usr/bin` and  `/sbin`
* Or (what I believe to be the best solution) is to add another bin name for reload like `reload-js`, `reloadjs`, `node-reload`, and then have a note in the README telling Ubuntu users to delete the reload out of `/usr/bin` and use one of the alternative names. This allows us to keep the reload name on all other platforms which affects a great amount of the users. (Side note, npm should have their stuff install in a place with less of a priority so this conflict doesn't happen to others?)

**Comment by yamboy1** [comment]
This seems like a good idea. Better than having to rename everything

**Comment by yamboy1** [comment]
Maybe as well as having a note in the readme you should also mention it when the user runs `npm install reload -g`.

**Comment by ubershmekel** [comment]
This is a security risk. If I understand correctly - an ubuntu `npm install -g reload` exposes the entire filesystem to the network with root read privileges for a few minutes at startup. Asking ubuntu users to fix it manually is just waiting for an exploit and perhaps somewhat negligent. Personally this caused my jenkins to not load because of contention for port 8080 during startup.

The issue was tricky to figure out, and perhaps I was lucky to have the jenkins fail because that's all that clued me into this issue. I don't think you need to rename from `reload` but perhaps have the `npm install -g` do the path manipulation or actively fix the problem. Maybe the bin is renamed on ubuntu only. At the moment I'm just going to avoid using `reload` on ubuntu.

**Comment by kethinov** [comment]
This isn't really this project's fault though.

Since any npm module can give itself a `cli` name that takes precedence over `/sbin` in Ubuntu, the problem is either:

1. Ubuntu's fault for prioritizing `/usr/bin` over `/sbin` in the default PATH, or...
2. `npm`'s fault for depositing executables in a location that is a higher priority than `/sbin`.

The workaround suggested by @alallier is all that can be expected from this repo. And this is probably not the only npm module which surfaces this problem.

**Comment by kethinov** [comment]
Also it does not expose the entire filesystem to root read privileges. This is a PATH issue.

**Comment by yamboy1** [comment]
What if I use the npm [preinstall](https://coderwall.com/p/ajbibg/node-js-npm-preinstall) to change the name in the package.json?

**Comment by ubershmekel** [comment]
@kethinov my ubuntu launches `reload` on startup. It's a path issue which exposes the filesystem. See https://github.com/jprichardson/reload/issues/94

**Comment by kethinov** [comment]
Yes. It's a problem. But it's not a problem this repo needs to solve. It's a problem either Ubuntu or npm needs to solve for the reasons listed above. Until then, follow the workaround.

**Comment by kethinov** [comment]
Actually @yamboy1 that solution sounds interesting. It might be worth looking into. If we *do* possess a technical means of sniffing for Ubuntu and renaming `reload` just for Ubuntu users I think it's worth exploring.

**Comment by yamboy1** [comment]
Theres an npm preinstall command that could be useful.

**Comment by yamboy1** [comment]
What about if I make a script that runs [os.platform()](https://nodejs.org/api/os.html#os_os_platform) to find out if user is using linux. Then it can run a `whereis reload` command to see if reload is installed. So instead of just for ubuntu, rename it whenever it sees that `reload` command.

**Comment by yamboy1** [comment]
I'm not sure how to change the name though.
@alallier Any Ideas?

**Comment by kethinov** [comment]
In the case of an Ubuntu detection, could the preinstall script simply alter the package.json `cli` section to rename `reload` to `reloadjs` or whatever? Or is it too late by that point?

**Comment by yamboy1** [comment]
what do you mean by the `cli` section?

**Comment by kethinov** [comment]
I mean't the [bin](https://github.com/jprichardson/reload/blob/bef767a822c43183db0239980e26f28d13012495/package.json#L40) section.

What I'm wondering is if the preinstall script alters that line to change it from `reload` to `reloadjs`, I wonder if that's early enough in the install procedure to change where npm drops the executable in Ubuntu only.

**Comment by yamboy1** [comment]
Maybe it would be better to use a postinstall to make the changes afterwards

**Comment by yamboy1** [comment]
Using the preinstall would be the best option, but how do we get access to the package.json before it gets installed?

**Comment by kethinov** [comment]
The postinstall idea is a good idea too. You could basically automate the workaround that way and no one would ever know it's even happening unless they looked under the hood. ;)

**Comment by yamboy1** [comment]
How would I find the package for the post install?

**Comment by kethinov** [comment]
One approach:

1. Check if the OS is any kind of Linux
2. If so, use node's `exec` feature to execute a bash command `which reload` to locate where the executable is
3. Check if the executable is a symlink
4. If so, check that the symlink points to a location with `node_modules` in its path to ensure that npm put the executable there
5. If all of the above are true, rename the executable to `reloadjs`

**Comment by yamboy1** [comment]
That seems great. Will work on it soon.

**Comment by yamboy1** [comment]
@kethinov Would it be better to check for `/sbin/reload, and only change the name if it can be found.

**Comment by kethinov** [comment]
The solution should be agnostic to the naming conflict. The idea behind the five step process above is to identify any potential naming conflict that preexists in the operating system, including but not limited to Ubuntu. That way you will catch `/sbin/reload` but if some other reload is installed by default on some other system it will catch that too.

**Comment by yamboy1** [comment]
@kethinov That makes sense

**Comment by bertho-zero** [comment]
I face to the same issue with Ubuntu 16.04.

**Comment by kethinov** [comment]
I recommend closing this as a wontfix for the following reasons:

1. It doesn't seem to be a problem in the latest Ubuntu anymore since the `reload` system command appears to have been renamed.
2. I spent some time prototyping the above-described solution in a postinstall script and ran into trouble with `which` giving wrong answers.
3. It remains the case that this isn't really this project's fault. Again, since any npm module can give itself a `cli` name that takes precedence over `/sbin` in Ubuntu, the problem is either Ubuntu's fault for prioritizing `/usr/bin` over `/sbin` in the default PATH, or npm's fault for depositing executables in a location that is a higher priority than `/sbin`.

If anybody encounters a similar naming conflict like this in the future, a simple workaround is to alter your PATH to prioritize `/sbin` over `/usr/bin`, which is the case in—for instance—macOS.

**Comment by alallier** [comment]
Thanks for the write up @kethinov. This will be marked as won't fix.

Continuing discussions are welcome. Happy to re-open in the future if new evidence presents itself!
