### ISSUE TITLE
Command line broken on Mac

### ISSUE THREAD

**Issue by alallier** [alallier/reload#137]
Received an email stating the command line is broken on Mac.

Relevant email bits:

> I have used this on windows and it serves up all files as expected - works charm.

> I tried to host up an app on Mac and it wouldn't work - am i missing something.

(Need to confirm)

**Comment by alallier** [comment]
Confirmed working on Ubuntu.

**Comment by AckerApple** [comment]
I have tested on Mac. All I do all day is Mac. And on the surface reload seems to be working fine now from an NPM install. My educated guess is that someone reported this issue long after having the broken npm version previously published.

Reload peeps, I have updated my fork documentation on our differences since you have caught up even more as of late: https://www.npmjs.com/package/ack-reload#benefits-of-ack-reload-over-original-reload-package

**Comment by takrishna** [comment]
I installed "reload" using NPM command 
`"npm install -g reload"`

**Below is the folder I wanted to host and the command I used**
<img width="400" alt="screen shot 2017-08-08 at 8 24 10 pm" src="https://user-images.githubusercontent.com/5318967/29078659-a460e9ba-7c78-11e7-9d81-2f46d7aa3412.png">

**The results**
<img width="400" alt="screen shot 2017-08-08 at 8 09 27 pm" src="https://user-images.githubusercontent.com/5318967/29078107-1ef2b886-7c77-11e7-91cc-0e1f43e85b6d.png">

Problem:
1. I see index.html being served when I hit http://localhost:8080 - (Yet to explore what changing protocol status code means (101))
2. I don't see other files being served (e.g., .JS Files, CSS Files) - I receive 404s

**Heres what I tried:**
1. I tried without the `-d `attribute so that all folders can be served - and files from bower_components would resolve -> Result -> It actually didn't.
2. The app-launch.js file is present in the same location as index.html so I thought it would show me when I hit the URL: http://localhost:8080/app-launch.js -> Result -> It didn't.

Thanks for the help in advance guys.

**Comment by alallier** [comment]
@takrishna can you run `reload --version` for me too?

**Comment by alallier** [comment]
Is your HTML requesting anything from the `bower_components` folder? If nothing is requesting the file it won't be served.

**Comment by takrishna** [comment]
version would be 2.2.0 - is this the latest ? - Yep.. it is requesting app-launch.js, then some files from bower_components as well.. currently both are not being served.

**Comment by takrishna** [comment]
further what I observe is that I make http request via browser but I receive 101 status code with upgrade to something like "ws://localhost:8080" ws standing for web socket ?

**Comment by AckerApple** [comment]
You need to have 2.2.1 . We all know 2.2.0 is broke

**Comment by alallier** [comment]
Upgrade to the latest 2.2.1, 2.2.0 caused a regression. Let me know if this fixes your problem.

**Comment by alallier** [comment]
Just hand tested this in Mac and it is working on the latest version (2.2.1). Going to close, if this is still a problem. Please let me know and I can re-open this and investigate further.
