### ISSUE TITLE
remove dep upon express

### ISSUE THREAD

**Issue by jprichardson** [alallier/reload#4]

**Comment by AckerApple** [comment]
My pull request addresses this : https://github.com/jprichardson/reload/pull/62

**Comment by yamboy1** [comment]
@alallier What are we going to do about this?

**Comment by AckerApple** [comment]
I got rid of express by using serve-static. Follow my code. Weighs far less in file size. Does the same job reload leans on express for.

https://github.com/AckerApple/reload/blob/master/lib/reload.js#L49

**Comment by alallier** [comment]
Thanks for the tip @AckerApple we will look into it.

**Comment by alallier** [comment]
Closed by #132

**Comment by AckerApple** [comment]
I think you got a long way to go on this one. It seems only HTML files can be loaded, no?

Please check my findings:

I installed reload using ```npm install -g reload``` and then found a www folder and launched with ```reload -b```. Only the HTML file can load. No asset files like .js, .css ... ALSO, I cannot set url variables.

This is why I recommend node-static to serve the static files.

Am I totally wrong? Because then I did:

```npm uninstall -g reload" and then ```npm install -g reload@2.0.1``` and everything worked.

What's going on? So odd some choices being made, no?

**Comment by AckerApple** [comment]
It seems to me you published a completely broken version. Unit tests would have told you so.

**Comment by AckerApple** [comment]
I spent some time getting this to work just right in my fork: https://github.com/AckerApple/reload/blob/master/lib/reload.js#L51
